name: bookstore_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  google_sign_in: ^6.2.1
  cached_network_image: ^3.2.3
  http: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  persistent_bottom_nav_bar: ^6.2.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.7.5
  riverpod_lint: ^2.3.13
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/splash_logo.png
  color: "#ffffff"
  android_12:
    image: assets/splash_logo.png
    color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/google_fonts/
    - assets/books.json
    - assets/images/google_logo.png