// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-v86WaTaKr2gy_4jomXM0omTLSyvm-7c',
    appId: '1:896916827599:web:42dc6c8247d3565b73b6ba',
    messagingSenderId: '896916827599',
    projectId: 'bookstore-cd929',
    authDomain: 'bookstore-cd929.firebaseapp.com',
    storageBucket: 'bookstore-cd929.firebasestorage.app',
    measurementId: 'G-Z1LC50H7HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqb6TfxBJBWqdNTewhOHqAYsvjVoTX-9w',
    appId: '1:896916827599:android:5740d652c1adf8b773b6ba',
    messagingSenderId: '896916827599',
    projectId: 'bookstore-cd929',
    storageBucket: 'bookstore-cd929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-AwS8SxqskcCjQKIK20E5T8KlljE3qFE',
    appId: '1:896916827599:ios:7aff3f0fac2d386673b6ba',
    messagingSenderId: '896916827599',
    projectId: 'bookstore-cd929',
    storageBucket: 'bookstore-cd929.firebasestorage.app',
    androidClientId: '896916827599-pp1vln9o0vaec3su918avvgosfjgqa4u.apps.googleusercontent.com',
    iosClientId: '896916827599-t090pb1vsc1bg4a3k0u6rm0kk5cac7b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-AwS8SxqskcCjQKIK20E5T8KlljE3qFE',
    appId: '1:896916827599:ios:7aff3f0fac2d386673b6ba',
    messagingSenderId: '896916827599',
    projectId: 'bookstore-cd929',
    storageBucket: 'bookstore-cd929.firebasestorage.app',
    androidClientId: '896916827599-pp1vln9o0vaec3su918avvgosfjgqa4u.apps.googleusercontent.com',
    iosClientId: '896916827599-t090pb1vsc1bg4a3k0u6rm0kk5cac7b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-v86WaTaKr2gy_4jomXM0omTLSyvm-7c',
    appId: '1:896916827599:web:5898cbf529c7da7b73b6ba',
    messagingSenderId: '896916827599',
    projectId: 'bookstore-cd929',
    authDomain: 'bookstore-cd929.firebaseapp.com',
    storageBucket: 'bookstore-cd929.firebasestorage.app',
    measurementId: 'G-1ZJXL4NSEY',
  );

}